const LOAD_FIRST_DATA = 'LOAD_FIRST_DATA';
const CHANGE_BALL_VALUE_FIRST = 'CHANGE_BALL_VALUE_FIRST';
const CHANGE_BALL_VALUE_SECOND = 'CHANGE_BALL_VALUE_SECOND';
const CHANGE_MIN = 'CHANGE_MIN';
const CHANGE_MAX = 'CHANGE_MAX';
const CHANGE_VALUE_FIRST = 'CHANGE_VALUE_FIRST';
const CHANGE_VALUE_SECOND = 'CHANGE_VALUE_SECOND';
const DISABLE_RUNNERS_VALUES = 'DISABLE_RUNNERS_VALUES';
const TOGGLE_VERTICAL_POSITION = 'TOGGLE_VERTICAL_POSITION';
const ENABLE_ONE_RUNNER = 'ENABLE_ONE_RUNNER';
const CHANGE_STEP = 'CHANGE_STEP';

export {
    LOAD_FIRST_DATA,
    CHANGE_BALL_VALUE_FIRST,
    CHANGE_BALL_VALUE_SECOND,
    CHANGE_MIN,
    CHANGE_MAX,
    CHANGE_VALUE_FIRST,
    CHANGE_VALUE_SECOND,
    DISABLE_RUNNERS_VALUES,
    TOGGLE_VERTICAL_POSITION,
    ENABLE_ONE_RUNNER,
    CHANGE_STEP,
}