const LOAD_FIRST_DATA = 'LOAD_FIRST_DATA';
const CHANGE_BALL_VALUE_FIRST = 'CHANGE_BALL_VALUE_FIRST';
const CHANGE_BALL_VALUE_SECOND = 'CHANGE_BALL_VALUE_SECOND';
const CHANGE_STATE = 'CHANGE_STATE';

export {
    LOAD_FIRST_DATA,
    CHANGE_BALL_VALUE_FIRST,
    CHANGE_BALL_VALUE_SECOND,
    CHANGE_STATE 
}